/**
 * Seed the `matches` table from api-football fixtures.
 *
 * Prerequisites:
 *   - teams already seeded (`npm run seed:teams`)
 *   - API_FOOTBALL_KEY and SUPABASE_SERVICE_ROLE_KEY in .env.local
 *
 * Idempotent (upsert on external_id). Writes `supabase/seed-fixtures.sql`
 * so future `db:reset` runs replay the data without hitting the API.
 */

import { writeFile } from "node:fs/promises";
import path from "node:path";

import { createApiFootballClient } from "@/lib/api-football/client";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

const LEAGUE_WORLD_CUP = 1;
const SEASON = 2026;

type Fixture = {
  fixture: {
    id: number;
    date: string;
    status: { short: string };
  };
  league: { round: string };
  teams: {
    home: { id: number };
    away: { id: number };
  };
};

type SeedMatch = {
  external_id: number;
  stage: "group";
  group_letter: string;
  home_team_id: number;
  away_team_id: number;
  scheduled_at: string;
};

function parseGroupRound(round: string): string | null {
  // api-football rounds for the group stage look like "Group A - 1".
  const match = /^Group\s+([A-L])/i.exec(round);
  return match?.[1]?.toUpperCase() ?? null;
}

function quoteSql(value: string | null) {
  if (value === null) return "null";
  return `'${value.replace(/'/g, "''")}'`;
}

async function fetchFixtures(apiKey: string): Promise<Fixture[]> {
  const url = new URL("https://v3.football.api-sports.io/fixtures");
  url.searchParams.set("league", String(LEAGUE_WORLD_CUP));
  url.searchParams.set("season", String(SEASON));
  const res = await fetch(url, { headers: { "x-apisports-key": apiKey } });
  if (!res.ok) {
    throw new Error(`api-football /fixtures returned ${res.status}: ${await res.text()}`);
  }
  const body = (await res.json()) as { response: Fixture[] };
  return body.response;
}

async function main() {
  // We need the api key for fixtures even if our typed client doesn't expose
  // /fixtures yet (kept lightweight to avoid adding seldom-used surface area).
  const apiKey = process.env.API_FOOTBALL_KEY;
  if (!apiKey) throw new Error("API_FOOTBALL_KEY is not set");
  // Sanity-check the typed client too so misconfig surfaces early.
  createApiFootballClient({ apiKey });

  const supabase = createSupabaseAdminClient();

  console.log("Loading teams from DB...");
  const { data: teams, error: teamsError } = await supabase
    .from("teams")
    .select("id, external_id, name");
  if (teamsError) throw teamsError;
  if (!teams || teams.length === 0) {
    throw new Error("No teams in DB. Run `npm run seed:teams` first.");
  }
  const externalToInternal = new Map<number, number>();
  for (const t of teams) {
    if (t.external_id != null) externalToInternal.set(t.external_id, t.id);
  }
  console.log(`  -> ${externalToInternal.size} teams indexed`);

  console.log(`Fetching fixtures for league=${LEAGUE_WORLD_CUP} season=${SEASON}...`);
  const fixtures = await fetchFixtures(apiKey);
  console.log(`  -> ${fixtures.length} fixtures total`);

  const groupFixtures = fixtures.filter((f) => parseGroupRound(f.league.round));
  console.log(`  -> ${groupFixtures.length} group-stage fixtures`);

  const seeds: SeedMatch[] = [];
  const skipped: Array<{ id: number; reason: string }> = [];
  for (const f of groupFixtures) {
    const group = parseGroupRound(f.league.round);
    const home = externalToInternal.get(f.teams.home.id);
    const away = externalToInternal.get(f.teams.away.id);
    if (!group || !home || !away) {
      skipped.push({ id: f.fixture.id, reason: !group ? "no group" : "team missing" });
      continue;
    }
    seeds.push({
      external_id: f.fixture.id,
      stage: "group",
      group_letter: group,
      home_team_id: home,
      away_team_id: away,
      scheduled_at: f.fixture.date,
    });
  }
  if (skipped.length > 0) {
    console.warn(`  -> skipped ${skipped.length}:`, skipped.slice(0, 5));
  }

  console.log("Upserting into Supabase...");
  const { error } = await supabase
    .from("matches")
    .upsert(seeds, { onConflict: "external_id" });
  if (error) throw error;
  console.log(`  -> ok (${seeds.length} rows)`);

  console.log("Writing supabase/seed-fixtures.sql...");
  const sqlLines = [
    "-- Generated by scripts/seed-fixtures.ts. Re-run `npm run seed:fixtures` to refresh.",
    "-- Idempotent: ON CONFLICT updates the row. Assumes seed.sql (teams) ran first.",
    "",
    "insert into matches (external_id, stage, group_letter, home_team_id, away_team_id, scheduled_at) values",
  ];
  const rows = seeds.map(
    (s, i) =>
      `  (${s.external_id}, 'group', ${quoteSql(s.group_letter)}, ${s.home_team_id}, ${s.away_team_id}, ${quoteSql(s.scheduled_at)})${i === seeds.length - 1 ? "" : ","}`,
  );
  sqlLines.push(...rows);
  sqlLines.push("on conflict (external_id) do update set");
  sqlLines.push("  stage = excluded.stage,");
  sqlLines.push("  group_letter = excluded.group_letter,");
  sqlLines.push("  home_team_id = excluded.home_team_id,");
  sqlLines.push("  away_team_id = excluded.away_team_id,");
  sqlLines.push("  scheduled_at = excluded.scheduled_at;");

  const outPath = path.resolve("supabase/seed-fixtures.sql");
  await writeFile(outPath, `${sqlLines.join("\n")}\n`, "utf8");
  console.log(`  -> wrote ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
