/**
 * Seed the `teams` table from api-football.
 *
 * Usage:
 *   1. Set API_FOOTBALL_KEY and SUPABASE_SERVICE_ROLE_KEY in .env.local
 *   2. Ensure `supabase start` is running (or point to a remote project)
 *   3. `npm run seed:teams`
 *
 * The script is idempotent (upsert on external_id). It also writes the result
 * as a SQL file to `supabase/seed.sql` so future `supabase db reset` runs
 * don't need to hit api-football again.
 */

import { writeFile } from "node:fs/promises";
import path from "node:path";

import {
  createApiFootballClient,
  type ApiFootballStanding,
  type ApiFootballTeam,
} from "@/lib/api-football/client";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

// Env vars are loaded via tsx --env-file (see `seed:teams` script in package.json).

const LEAGUE_WORLD_CUP = 1;
const SEASON = 2026;

// api-football mis-codes (or omits) FIFA codes for a few teams. Override by
// their api-football team id so the upsert on `fifa_code` (UNIQUE) doesn't
// collide. Codes are FIFA's official 3-letter abbreviations.
const FIFA_CODE_OVERRIDES: Record<number, string> = {
  775: "AUT", // Austria (api-football returns AUS, colliding with Australia)
  22: "IRN", // Iran (api-football returns IRA, colliding with Iraq)
  1567: "IRQ", // Iraq (api-football returns IRA)
  5530: "CUW", // Curaçao (api-football returns null)
};

type SeedTeam = {
  external_id: number;
  name: string;
  fifa_code: string;
  group_letter: string | null;
  flag_url: string | null;
};

function buildGroupIndex(standingsGroups: ApiFootballStanding[][]) {
  const index = new Map<number, string>();
  for (const group of standingsGroups) {
    for (const standing of group) {
      // "Group A" -> "A"
      const letter = standing.group.replace(/^Group\s+/i, "").slice(0, 1);
      index.set(standing.team.id, letter);
    }
  }
  return index;
}

function toSeed(team: ApiFootballTeam, group: string | null): SeedTeam {
  const override = FIFA_CODE_OVERRIDES[team.team.id];
  const fifaCode =
    override ??
    team.team.code?.toUpperCase() ??
    team.team.name.replace(/[^A-Z]/gi, "").slice(0, 3).toUpperCase();
  return {
    external_id: team.team.id,
    name: team.team.name,
    fifa_code: fifaCode,
    group_letter: group,
    flag_url: team.team.logo,
  };
}

function quoteSql(value: string | null) {
  if (value === null) return "null";
  return `'${value.replace(/'/g, "''")}'`;
}

async function main() {
  const api = createApiFootballClient();
  const supabase = createSupabaseAdminClient();

  console.log(`Fetching teams for league=${LEAGUE_WORLD_CUP} season=${SEASON}...`);
  const teams = await api.listTeams({ league: LEAGUE_WORLD_CUP, season: SEASON });
  console.log(`  -> ${teams.length} teams`);

  console.log("Fetching standings (for group letters)...");
  const standings = await api.listStandings({
    league: LEAGUE_WORLD_CUP,
    season: SEASON,
  });
  const groupIndex = standings[0]
    ? buildGroupIndex(standings[0].league.standings)
    : new Map<number, string>();
  console.log(`  -> ${groupIndex.size} teams indexed by group`);

  const seeds: SeedTeam[] = teams.map((t) =>
    toSeed(t, groupIndex.get(t.team.id) ?? null),
  );

  console.log("Upserting into Supabase...");
  const { error } = await supabase
    .from("teams")
    .upsert(seeds, { onConflict: "external_id" });
  if (error) throw error;
  console.log(`  -> ok (${seeds.length} rows)`);

  console.log("Writing supabase/seed.sql...");
  const sqlLines = [
    "-- Generated by scripts/seed-teams.ts. Re-run `npm run seed:teams` to refresh.",
    "-- Idempotent: ON CONFLICT updates the row.",
    "",
    "insert into teams (external_id, name, fifa_code, group_letter, flag_url) values",
  ];
  const rows = seeds.map(
    (s, i) =>
      `  (${s.external_id}, ${quoteSql(s.name)}, ${quoteSql(s.fifa_code)}, ${quoteSql(
        s.group_letter,
      )}, ${quoteSql(s.flag_url)})${i === seeds.length - 1 ? "" : ","}`,
  );
  sqlLines.push(...rows);
  sqlLines.push("on conflict (external_id) do update set");
  sqlLines.push("  name = excluded.name,");
  sqlLines.push("  fifa_code = excluded.fifa_code,");
  sqlLines.push("  group_letter = excluded.group_letter,");
  sqlLines.push("  flag_url = excluded.flag_url;");

  const outPath = path.resolve("supabase/seed.sql");
  await writeFile(outPath, `${sqlLines.join("\n")}\n`, "utf8");
  console.log(`  -> wrote ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
